name: CI
on: [push, pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: |
          **/setup.py

    - name: Install development dependencies
      run: |
        pip install .[dev]
        pip list -v

    - name: pylint
      run: pylint nari/ext/act

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: |
          **/setup.py

    - name: Install development dependencies
      run: |
        pip install .[dev]
        pip list -v

    - name: unittest
      run: python -munittest

  types:
    name: Check Types
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: |
          **/setup.py

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: '1.62.0'

    - name: Install development dependencies
      run: |
        pip install setuptools-rust
        pip install .[dev]
        pip list -v

    - name: mypy
      run: mypy --namespace-packages --explicit-package-bases nari
